# https://cert-manager.io/docs/installation/helm/
resource "helm_release" "do-cert-manager" {
  provider = helm.do

  name       = "cert-manager"
  repository = "https://charts.jetstack.io"
  chart      = "cert-manager"
  version    = "1.6.1"

  # values = [yamlencode({})]

  depends_on = [
    module.do-cert-manager-crds
  ]
}

# ./cert-manager.crds was generated by
# earthly +cert-manager.crds
module "do-cert-manager-crds" {
  source = "./cert-manager.crds"
  providers = {
    kubernetes = kubernetes.do
  }
}
