[tools]
opentofu = "1.13.1"
"github:opentofu/tofu-ls" = "0.5.3"

# kubectl should always match the k8s cluster minor version
# To find the cluster version, run `doctl k8s cluster list`
kubectl = "1.33"

doctl = "1"
k9s = "latest"
