version: '3'
services:
  workspace:
    image: haxe/terraform_devcontainer_workspace:20240604034917
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ..:/workspace:cached
    environment:
      - EARTHLY_SECRET_FILES=envrc=/workspace/.envrc
      - EARTHLY_USE_INLINE_CACHE=true
      - EARTHLY_SAVE_INLINE_CACHE=true
    user: vscode
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
