version: '3'
services:
  workspace:
    image: haxe/terraform_devcontainer_workspace:20210904053412
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ..:/workspace:cached
    user: vscode
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
