name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  plan:
    runs-on: ubuntu-latest
    container: "haxe/terraform_devcontainer_workspace:20230405145655"
    env:
      TF_INPUT: 0
      TF_IN_AUTOMATION: 1
      AWS_DEFAULT_REGION: eu-west-1
    steps:
      - uses: actions/checkout@v3
      - run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
      - run: terraform plan -detailed-exitcode
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          SPACES_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
          SPACES_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
